const myquotes = [
    { "quote": "There is no much satisfying than hearing a big crowd go silent" },
    { "quote": "1% chance is enough to give 100%" },
    { "quote": "Play Bold!! Never Refrain" },
    { "quote": "Never forget the past it may be used in future" },
    { "quote": "Never Judge a book by its cover" },
    { "quote": "The only limit to our realization of tomorrow is our doubts of today." },
    { "quote": "Do not wait to strike till the iron is hot; but make it hot by striking." },
    { "quote": "Whether you think you can or think you can’t, you’re right." },
    { "quote": "The best way to predict the future is to invent it." },
    { "quote": "Life is 10% what happens to us and 90% how we react to it." },
    { "quote": "Good things come to those who wait, but better things come to those who go out and get them." },
    { "quote": "If you can dream it, you can achieve it." },
    { "quote": "The only way to do great work is to love what you do." },
    { "quote": "The future belongs to those who believe in the beauty of their dreams." },
    { "quote": "The best way to get started is to quit talking and begin doing." },
    { "quote": "Success is not the key to happiness. Happiness is the key to success." },
    { "quote": "Your time is limited, don't waste it living someone else's life." },
    { "quote": "Don't watch the clock; do what it does. Keep going." },
    { "quote": "You miss 100% of the shots you don’t take." },
    { "quote": "Act as if what you do makes a difference. It does." },
    { "quote": "Keep your face always toward the sunshine—and shadows will fall behind you." },
    { "quote": "Believe you can and you're halfway there." },
    { "quote": "What you get by achieving your goals is not as important as what you become by achieving your goals." },
    { "quote": "You are never too old to set another goal or to dream a new dream." },
    { "quote": "The only thing worse than starting something and failing is not starting something." },
    { "quote": "Don't be afraid to give up the good to go for the great." },
    { "quote": "It does not matter how slowly you go as long as you do not stop." },
    { "quote": "The way to get started is to quit talking and begin doing." },
    { "quote": "The pessimist sees difficulty in every opportunity. The optimist sees opportunity in every difficulty." },
    { "quote": "It always seems impossible until it’s done." },
    { "quote": "Success usually comes to those who are too busy to be looking for it." },
    { "quote": "If you really look closely, most overnight successes took a long time." },
    { "quote": "Hardships often prepare ordinary people for an extraordinary destiny." },
    { "quote": "The best revenge is massive success." },
    { "quote": "The difference between ordinary and extraordinary is that little extra." },
    { "quote": "The only place where success comes before work is in the dictionary." },
    { "quote": "Don't let what you cannot do interfere with what you can do." },
    { "quote": "Don't be afraid to give up the good to go for the great." },
    { "quote": "Success is not the absence of failure; it’s the persistence through failure." },
    { "quote": "The secret of success is to do the common thing uncommonly well." },
    { "quote": "Success is not how high you have climbed, but how you make a positive difference to the world." },
    { "quote": "If you are not willing to risk the usual, you will have to settle for the ordinary." },
    { "quote": "Opportunities don't happen. You create them." },
    { "quote": "Do one thing every day that scares you." },
    { "quote": "People who succeed have momentum. The more they succeed, the more they want to succeed." },
    { "quote": "Don’t let yesterday take up too much of today." },
    { "quote": "You learn more from failure than from success. Don’t let it stop you. Failure builds character." },
    { "quote": "If you are working on something that you really care about, you don’t have to be pushed. The vision pulls you." },
    { "quote": "Experience is a hard teacher because she gives the test first, the lesson afterwards." },
    { "quote": "To see what is right and not do it is a lack of courage." },
    { "quote": "The only way to achieve the impossible is to believe it is possible." },
    { "quote": "The road to success and the road to failure are almost exactly the same." },
    { "quote": "Setting goals is the first step in turning the invisible into the visible." },
    { "quote": "Believe you can and you're halfway there." },
    { "quote": "It’s not whether you get knocked down, it’s whether you get up." },
    { "quote": "Your limitation—it’s only your imagination." },
    { "quote": "Push yourself, because no one else is going to do it for you." },
    { "quote": "Great things never come from comfort zones." },
    { "quote": "Dream it. Wish it. Do it." },
    { "quote": "Success doesn’t just find you. You have to go out and get it." },
    { "quote": "The harder you work for something, the greater you’ll feel when you achieve it." },
    { "quote": "Dream bigger. Do bigger." },
    { "quote": "Don’t stop when you’re tired. Stop when you’re done." },
    { "quote": "Wake up with determination. Go to bed with satisfaction." },
    { "quote": "Do something today that your future self will thank you for." },
    { "quote": "Little things make big days." },
    { "quote": "It’s going to be hard, but hard does not mean impossible." },
    { "quote": "Don’t wait for opportunity. Create it." },
    { "quote": "Sometimes we’re tested not to show our weaknesses, but to discover our strengths." },
    { "quote": "The key to success is to focus on goals, not obstacles." },
    { "quote": "Dream it. Believe it. Build it." },
    { "quote": "Don't wait for the perfect moment, take the moment and make it perfect." },
    { "quote": "Success is walking from failure to failure with no loss of enthusiasm." },
    { "quote": "Do what you can with all you have, wherever you are." },
    { "quote": "Start where you are. Use what you have. Do what you can." },
    { "quote": "Successful people do what unsuccessful people are not willing to do. Don't wish it were easier; wish you were better." },
    { "quote": "Success seems to be connected with action. Successful people keep moving. They make mistakes, but they don’t quit." },
    { "quote": "The road to success and the road to failure are almost exactly the same." },
    { "quote": "You are never too old to set another goal or to dream a new dream." },
    { "quote": "To accomplish great things, we must not only act, but also dream, not only plan, but also believe." },
    { "quote": "We may encounter many defeats but we must not be defeated." },
    { "quote": "Always do your best. What you plant now, you will harvest later." },
    { "quote": "The secret of getting ahead is getting started." },
    { "quote": "If you really look closely, most overnight successes took a long time." },
    { "quote": "Our greatest glory is not in never falling, but in rising every time we fall." },
    { "quote": "You can waste your lives drawing lines. Or you can live your life crossing them." },
    { "quote": "When you stop chasing the wrong things, you give the right things a chance to catch you." },
    { "quote": "If you are not willing to risk the usual, you will have to settle for the ordinary." },
    { "quote": "To be successful you must accept all challenges that come your way. You can't just accept the ones you like." },
    { "quote": "Challenges are what make life interesting and overcoming them is what makes life meaningful." },
    { "quote": "He who is not courageous enough to take risks will accomplish nothing in life." },
    { "quote": "Success is not final, failure is not fatal: It is the courage to continue that counts." },
    { "quote": "No one can make you feel inferior without your consent." },
    { "quote": "Believe you can and you’re halfway there." },
    { "quote": "What lies behind us and what lies before us are tiny matters compared to what lies within us." },
    { "quote": "The only way to achieve the impossible is to believe it is possible." },
    { "quote": "The only limit to our realization of tomorrow will be our doubts of today." },
    { "quote": "What you get by achieving your goals is not as important as what you become by achieving your goals." },
    { "quote": "Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful." },
    { "quote": "Success is not in what you have, but who you are." },
    { "quote": "Do not go where the path may lead, go instead where there is no path and leave a trail." },
    {"quote":"Sky is the limit"}
  ];
  
  
  export function getRandomQuote() {
    const index = Math.floor(Math.random() * myquotes.length);
    return myquotes[index].quote;
  }